"""
Django settings for Gather project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url

from decouple import config, Csv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


###################################################################################################################################################
# Environment variables
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='dev-secret-key')
if not SECRET_KEY:
    # Allow running locally even if .env has an empty SECRET_KEY
    SECRET_KEY = 'dev-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# File setting up database
if os.name == 'nt':
    try:
        import osgeo
        osgeo_dir = os.path.dirname(osgeo.__file__)
        os.environ['PATH'] = osgeo_dir + ';' + os.environ['PATH']
        os.environ['PROJ_LIB'] = os.path.join(osgeo_dir, 'data', 'proj') + ';' + os.environ.get('PROJ_LIB', '')
        
        import glob
        # Dynamically set GDAL and GEOS library paths for Django
        gdal_dlls = glob.glob(os.path.join(osgeo_dir, 'gdal*.dll'))
        if gdal_dlls:
            GDAL_LIBRARY_PATH = gdal_dlls[0]
            
        geos_dlls = glob.glob(os.path.join(osgeo_dir, 'geos_c*.dll'))
        if geos_dlls:
            GEOS_LIBRARY_PATH = geos_dlls[0]
    except ImportError:
        print("Warning: osgeo module not found. GDAL/GEOS may not work correctly.")
        pass

GOOGLE_API_KEY = config('GOOGLE_API_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gather.apps.GatherConfig',
    'django.contrib.gis',




]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gathertravel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gathertravel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': "postgis_ruby",
#         "USER": 'postgres',
#         "PASSWORD": 'ajk123',
#         "HOST": 'localhost'

#     }
# }


# Database
# Use DATABASE_URL when provided; otherwise fall back to the default values
# that were previously hard-coded for local PostGIS development.
DATABASE_URL = config(
    'DATABASE_URL',
    default='postgresql://postgres:postgres@localhost:5432/postgis_36_sample'
)
_db = dj_database_url.parse(DATABASE_URL)
_db['ENGINE'] = 'django.contrib.gis.db.backends.postgis'

DATABASES = {'default': _db}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'gather/static')]
STATIC_ROOT = BASE_DIR / "staticfiles_build" / "static"

MEDIA_ROOT = os.path.join(BASE_DIR, 'gather/media')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
